#TODO: Change version
version: 'v1.0.0.{build}'

cache:
  - Package
  
environment:
  STOREPASS:
    secure: l9BZEU39F1a4vSkhwl0CHR+yh6CD1c7byGzMv+1NUa4=

  matrix:
  ##### msvc 2017 ########
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GENERATORS: "Visual Studio 15 2017"
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    BUILD_ARCH: x86
    
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GENERATORS: "Visual Studio 15 2017 Win64"
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    BUILD_ARCH: x64
    
  ##### msvc 2015 ########
  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 14 2015"
    TOOLCHAIN_VERSION: 14
    QT_ROOT: C:\Qt\5.9\msvc2015
    BUILD_ARCH: x86
    
  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 14 2015 Win64"
    TOOLCHAIN_VERSION: 14
    QT_ROOT: C:\Qt\5.10\msvc2015_64
    BUILD_ARCH: x64
    
  ##### mingw ########
  - BUILD_TARGERT: windows_mingw
    GENERATORS: "MSYS Makefiles"
    TOOLCHAIN_VERSION: 530_32
    BUILD_ARCH: x86
    
  ##### android ########
  - BUILD_TARGERT: android
    GENERATORS: "MSYS Makefiles"
    BUILD_ARCH: "armeabi-v7a"
    ANDROID_ARM_NEON: ON
    ANDROID_API: android-29
    TOOLCHAIN_VERSION: 4.9
    
  - BUILD_TARGERT: android
    GENERATORS: "MSYS Makefiles"
    BUILD_ARCH: "arm64-v8a"
    ANDROID_ARM_NEON: ON
    ANDROID_API: android-29
    TOOLCHAIN_VERSION: 4.9
    
matrix:
  fast_finish: false

init:
  - set varch=%BUILD_ARCH%
  - if "%BUILD_ARCH%" == "x64" set varch=amd64
  - if "%BUILD_TARGERT%" == "windows_msvc" if %TOOLCHAIN_VERSION% LSS 15 (call "C:\Program Files (x86)\Microsoft Visual Studio %TOOLCHAIN_VERSION%.0\VC\vcvarsall.bat" %varch%) else (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %varch%)  
  - echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%
  - echo PROCESSOR_IDENTIFIER=%PROCESSOR_IDENTIFIER%
  #- if "%BUILD_TARGERT%" == "windows_mingw" set MSYSTEM=MINGW32  #设置编译系统为MINGW32
  - del C:\msys64\usr\bin\link.exe

install:
  - C:\msys64\autorebase.bat
  - C:\msys64\usr\bin\pacman.exe -S --noconfirm unzip
  #- if "%BUILD_TARGERT%"=="windows_mingw" set PATH=C:\Qt\Tools\mingw%TOOLCHAIN_VERSION%_32\bin;%PATH%
  - if "%BUILD_TARGERT%" == "windows_mingw" set MSYSTEM=MINGW32  #设置编译系统为MINGW32

before_build:

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake .. -G"%GENERATORS%" -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --target install

artifacts:
  
test: off

deploy:
  #provider: FTP 
  #protocol: sftp 
  #host: frs.sourceforge.net 
  #username: kl222,rabbitim
  #密码用这个加密 https://ci.appveyor.com/tools/encrypt
  #password:
  #  secure: 2WEtOQrdty3V3g0aEVvS3Q==
  #folder: pfs  #link pfs to /home/frs/project/r/ra/rabbitim
  #draft: false
  #active_mode: false
  #on:
    #branch: master

  - provider: GitHub
    #token : https://github.com/settings/tokens password encrypt: https://ci.appveyor.com/tools/encrypt
    auth_token:
      secure: xgIFN2iAfgj1gsWabdHrmFXvj0rce/ZWtKUwm3aDUNfLGu+kO/q94MYD8a46AbDL
    #artifact: RabbitGIS_$(BUILD_TARGERT)$(TOOLCHAIN_VERSION)_$(AUTOBUILD_ARCH)_$(QT_VERSION)_v$(appveyor_build_version)
    #draft: true
    #prerelease: true
    force_update: true
    on:
      BUILD_TARGERT: windows_msvc
      TOOLCHAIN_VERSION: 14
      BUILD_ARCH: x86
      appveyor_repo_tag: true        # deploy on tag push only
